[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "project_name"
version = "0.1.0"
description = "Descreva seu projeto aqui"
authors = [{name = "Vinicius Foreste"}]
dependencies = []
license = "MIT"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
minversion = "6.0"
testpaths = ["tests"]

[tool.ruff]
line-length = 88
select = ["E", "F", "W", "I"]
src = ["src"]
